
DROP TABLE "NSOAWARE"."MONITOR_T_ZCCZ";
CREATE TABLE "NSOAWARE"."MONITOR_T_ZCCZ" (
  "TID" VARCHAR2(255 BYTE) NOT NULL,
  "POSUMMARY" VARCHAR2(255 BYTE),
  "SYSNCSTATUS" NUMBER(2,0),
  "SYSNCMESSAGE" VARCHAR2(500 BYTE),
  "SYSNCDATE" DATE,
  "ISNEW" NUMBER(2,0),
  "TBR" VARCHAR2(255 BYTE)
)
TABLESPACE "NSOAWARE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Checks structure for table MONITOR_T_ZCCZ
-- ----------------------------
ALTER TABLE "NSOAWARE"."MONITOR_T_ZCCZ" ADD CONSTRAINT "SYS_C00136451" CHECK ("TID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
